var stations = [
    { name: "Alvesta" },
    { name: "Bergåsa" },
    { name: "Bromölla" },
    { name: "Bräkne-Hoby" },
    { name: "Båstad" },
    { name: "CPH Airport" },
    { name: "Emmaboda" },
    { name: "Eslöv" },
    { name: "Falkenberg" },
    { name: "Göteborg C" },
    { name: "Halmstad C" },
    { name: "Helsingborg C" },
    { name: "Hovmantorp" },
    { name: "Hyllie" },
    { name: "Hässleholm C" },
    { name: "Höör" },
    { name: "Kalmar C" },
    { name: "Karlshamn" },
    { name: "Karlskrona" },
    { name: "Kristianstad" },
    { name: "Kungsbacka" },
    { name: "Kävlinge" },
    { name: "København H" },
    { name: "Laholm" },
    { name: "Landskrona" },
    { name: "Lessebo" },
    { name: "Lund C" },
    { name: "Malmö C" },
    { name: "Mölndal" },
    { name: "Mörrum" },
    { name: "Nybro" },
    { name: "Osby" },
    { name: "Ramlösa" },
    { name: "Ronneby" },
    { name: "Sölvesborg" },
    { name: "Triangeln" },
    { name: "Tårnby" },
    { name: "Varberg" },
    { name: "Växjö" },
    { name: "Älmhult" },
    { name: "Ängelholm" },
    { name: "Åsa" },
    { name: "Ørestad" }
];

module.exports = stations;
